package controller;

public enum Action {
	MIDDLE, LOAD_SEED, A, CONG_LIN, BTN_GENERATE_CONG_LIN, CONG_MUL, BTN_GENERATE_CONG_MULTI, VARIANCE, STOCKING_TEST, DISTRIBUTION, GENERATE_VALUES, BTN_GENERATE_STACKING,
	APPLY_CHI, POKER
}
